# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfd73f4272e6b1947427632a8e83109de454d66e1c0af3fe155901839ac1580d7f7ef4ae09ca84aabd4eeaf576fbdcdf002cff44a6a2709413a4238c4e38d55b

test:
  secret_key_base: cc03485cceb202c98d38b094eac6b617f624e080064ef53ab13abe9cea7815f517d3a8873f272c3a2073c25633b247063dac76427e5a7f0f26bba23cbdb0d110

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
